version: '3.8'

services:
  # PostgreSQL Database (optional, for production)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-camf_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-camf_password}
      POSTGRES_DB: ${POSTGRES_DB:-camf_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U camf_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and queuing (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # CAMF Application
  camf:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://camf_user:camf_password@postgres:5432/camf_db
      - REDIS_URL=redis://redis:6379
      - STORAGE_DIR=/app/data/storage
      - TEMP_DIR=/app/data/temp
    volumes:
      - ./data:/app/data
      - ./detectors:/app/detectors
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx for production (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - camf

volumes:
  postgres_data: